### ISSUE TITLE
Does not work for addons that do not use ember-data

### ISSUE THREAD

**Issue by devotox** [ember-cli/ember-cli-update-codemods-manifest#90]
With the update of ember-data-codemod this issue arises

```
TypeError: Invalid Version: undefined
    at new SemVer (/Users/devonte/.config/yarn/global/node_modules/boilerplate-update/node_modules/semver/semver.js:315:11)
    at compare (/Users/devonte/.config/yarn/global/node_modules/boilerplate-update/node_modules/semver/semver.js:648:10)
    at Function.gte (/Users/devonte/.config/yarn/global/node_modules/boilerplate-update/node_modules/semver/semver.js:704:10)
    at keys.every.key (/Users/devonte/.config/yarn/global/node_modules/boilerplate-update/src/get-applicable-codemods.js:33:55)
    at Array.every (<anonymous>)
    at Object.entries.filter (/Users/devonte/.config/yarn/global/node_modules/boilerplate-update/src/get-applicable-codemods.js:33:35)
    at Array.filter (<anonymous>)
    at getApplicableCodemods (/Users/devonte/.config/yarn/global/node_modules/boilerplate-update/src/get-applicable-codemods.js:31:35)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by kellyselden** [comment]
cc @mszabo-wikia This may be related to https://github.com/kellyselden/boilerplate-update/pull/176?

**Comment by mszabo-wikia** [comment]
interesting... does it still happen with the latest ember-cli?

**Comment by devonte-tw** [comment]
Yes definitely does @mszabo-wikia

**Comment by kellyselden** [comment]
I just tested this without problem. Can you give steps to reproduce?
